/**
 * Mock Service Engine
 * Provides fallback mock data and real-time generation simulation
 * when FastAPI backend is offline during frontend development/testing.
 */
import { getStoredPresentations, saveStoredPresentation, deleteStoredPresentation } from '../utils/storage';

export const mockService = {
  async listPresentations() {
    await new Promise((r) => setTimeout(r, 120));
    return getStoredPresentations();
  },

  async getPresentation(id) {
    await new Promise((r) => setTimeout(r, 100));
    const list = getStoredPresentations();
    const item = list.find((p) => p.id === id);
    if (!item) throw new Error(`Presentation with id '${id}' not found`);
    return item;
  },

  async createPresentation(payload) {
    await new Promise((r) => setTimeout(r, 200));
    const now = new Date().toISOString();
    const newPresentation = {
      id: `deck-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`,
      title: payload.title || 'Untitled Presentation',
      theme: payload.theme || 'default',
      markdown: payload.markdown || `--- \nmarp: true\ntheme: ${payload.theme || 'default'}\npaginate: true\n---\n\n# ${payload.title || 'New Presentation'}\n\n- Welcome to MARP Slide Studio`,
      createdAt: now,
      updatedAt: now,
    };
    saveStoredPresentation(newPresentation);
    return newPresentation;
  },

  async updatePresentation(id, data) {
    await new Promise((r) => setTimeout(r, 150));
    const list = getStoredPresentations();
    const existing = list.find((p) => p.id === id);
    if (!existing) throw new Error(`Presentation with id '${id}' not found`);
    const updated = { ...existing, ...data, id, updatedAt: new Date().toISOString() };
    saveStoredPresentation(updated);
    return updated;
  },

  async deletePresentation(id) {
    await new Promise((r) => setTimeout(r, 100));
    deleteStoredPresentation(id);
    return { success: true, id };
  },

  async renderPreview(markdown, options = {}) {
    await new Promise((r) => setTimeout(r, 80));
    return {
      status: 'rendered',
      markdown,
      renderedAt: new Date().toISOString(),
    };
  },

  async exportPresentation(id, format = 'html') {
    await new Promise((r) => setTimeout(r, 300));
    if (format === 'pptx') {
      throw new Error('PowerPoint export requires the configured backend export service.');
    }
    const presentation = await this.getPresentation(id);
    return {
      success: true,
      format,
      filename: `${presentation.title.toLowerCase().replace(/\s+/g, '-')}.${format}`,
      downloadUrl: `data:text/plain;charset=utf-8,${encodeURIComponent(presentation.markdown)}`,
    };
  },

  async generateSlide(prompt, options = {}) {
    await new Promise((r) => setTimeout(r, 400));
    return {
      taskId: `task-${Date.now().toString(36)}`,
      status: 'queued',
      prompt,
      generatedSlideMarkdown: `\n\n---\n\n## AI Generated: ${prompt}\n\n- Context-aware automated slide points\n- Formatted strictly according to MARP directives\n- High clarity and structured delivery\n`,
    };
  },

  async generateContent(prompt, context = '') {
    await new Promise((r) => setTimeout(r, 500));
    return {
      taskId: `task-${Date.now().toString(36)}`,
      generatedMarkdown: `---
marp: true
theme: default
paginate: true
header: "AI Slide Studio"
footer: "Generated Presentation"
---

<!-- _class: lead -->
# ${prompt}
### Generated by MARP Presentation Agent

---

## Executive Strategy

- Strategic objective aligned with user intent
- High impact deliverables with clear milestones
- Measurable ROI and operational velocity

---

<!-- _backgroundColor: #0f172a -->
<!-- _color: #ffffff -->
## Projected Results

- **Performance**: 3.5x Faster authoring lifecycle
- **Standardization**: 100% MARP compliant themes
- **Team Velocity**: Continuous presentation CI/CD

---

# Next Steps

1. Review and refine slide directives
2. Export to PDF or HTML
3. Present live to stakeholders
`,
    };
  },
};
