import React, { useMemo, useState } from 'react';
import { Activity, Bot, Check, FileImage, Flag, FolderKanban, Gauge, LayoutDashboard, Layers3, Menu, Palette, PanelLeft, Save, Settings, Shield, Sparkles, Sun, Upload, Users, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import SlideView from '../components/presentation/SlideView';
import { parseMarpPresentation } from '../utils/marpParser';
import { canAdmin, getAdminRolePermissions, getPortalAdminUser } from '../services/adminAuthAdapter';
import { useMarpConfig } from '../context/MarpConfigContext';
import { useTheme } from '../context/ThemeContext';

const NAV = [
  ['overview', 'Overview', Gauge], ['landing', 'Landing Page', Sparkles], ['dashboard', 'Dashboard', LayoutDashboard], ['templates', 'Templates', Layers3], ['themes', 'Presentation Themes', Palette], ['ai', 'AI Configuration', Bot], ['visuals', 'Animations & Visuals', Activity], ['media', 'Media Library', FileImage], ['flags', 'Feature Flags', Flag], ['settings', 'General Settings', Settings], ['users', 'Users & Permissions', Users], ['activity', 'Activity Log', FolderKanban],
];
const sampleMarkdown = '---\nmarp: true\ntheme: default\n---\n\n# A considered idea\n\n- Clear hierarchy\n- Useful rhythm\n- Ready to present\n\n> Make the next step feel possible.';

export default function MarpAdminPage() {
  const navigate = useNavigate();
  const { draft, isDirty, updateDraft, resetDraft, publish } = useMarpConfig();
  const { theme, toggleTheme } = useTheme();
  const user = getPortalAdminUser();
  const [section, setSection] = useState('overview');
  const [collapsed, setCollapsed] = useState(false);
  const [toast, setToast] = useState('');
  const [selectedTheme, setSelectedTheme] = useState(draft.themes[0]?.id || 'default');
  const canWrite = canAdmin(user, 'settings:write');

  const update = (path, value) => updateDraft((current) => {
    const next = JSON.parse(JSON.stringify(current));
    const keys = path.split('.');
    let target = next;
    keys.slice(0, -1).forEach((key) => { target = target[key]; });
    target[keys[keys.length - 1]] = value;
    return next;
  });
  const saveDraft = () => { setToast('Draft saved locally'); window.setTimeout(() => setToast(''), 2200); };
  const publishChanges = () => { publish(user.name); setToast('Configuration published'); window.setTimeout(() => setToast(''), 2200); };
  const activeTheme = useMemo(() => draft.themes.find((item) => item.id === selectedTheme) || draft.themes[0], [draft.themes, selectedTheme]);
  const templateCount = draft.templates.filter((item) => item.active).length;

  if (!canAdmin(user, 'admin:read')) return <div className="admin-denied"><Shield size={32} /><h1>Admin access required</h1><p>Your IEEE Portal role does not have MARP administration access.</p><button onClick={() => navigate('/dashboard')}>Return to workspace</button></div>;

  return <div className={`marp-admin ${collapsed ? 'is-collapsed' : ''}`}>
    <aside className="admin-sidebar">
      <div className="admin-brand"><span><Layers3 size={18} /></span><strong>{draft.site.productName}</strong></div>
      <div className="admin-sidebar-label">Control plane</div>
      <nav aria-label="MARP administration">{NAV.map(([id, label, Icon]) => <button key={id} className={section === id ? 'is-active' : ''} onClick={() => setSection(id)} title={label}><Icon size={17} /><span>{label}</span></button>)}</nav>
      <div className="admin-sidebar-footer"><span>{user.name}</span><small>{user.role}</small></div>
    </aside>
    <main className="admin-main">
      <header className="admin-topbar"><button className="admin-icon-button" onClick={() => setCollapsed(!collapsed)} aria-label={collapsed ? 'Expand admin sidebar' : 'Collapse admin sidebar'}>{collapsed ? <PanelLeft size={18} /> : <Menu size={18} />}</button><div><span className="admin-breadcrumb">MARP Studio / Admin</span><h1>{NAV.find(([id]) => id === section)?.[1]}</h1></div><div className="admin-top-actions"><span className={`admin-dirty ${isDirty ? 'is-dirty' : ''}`}>{isDirty ? 'Unsaved changes' : 'Published'}</span><button className="admin-icon-button" onClick={toggleTheme} aria-label="Toggle appearance">{theme === 'dark' ? <Sun size={17} /> : <Sparkles size={17} />}</button><button className="admin-secondary-button" onClick={() => navigate('/dashboard')}>Exit admin</button></div></header>
      <div className="admin-content">{section === 'overview' && <Overview draft={draft} templateCount={templateCount} />}
        {section === 'landing' && <LandingEditor draft={draft} update={update} />}
        {section === 'dashboard' && <DashboardEditor draft={draft} update={update} />}
        {section === 'templates' && <TemplatesEditor draft={draft} update={update} />}
        {section === 'themes' && <ThemesEditor draft={draft} update={update} activeTheme={activeTheme} selectedTheme={selectedTheme} setSelectedTheme={setSelectedTheme} />}
        {section === 'ai' && <AIEditor draft={draft} update={update} />}
        {section === 'visuals' && <VisualsEditor draft={draft} update={update} />}
        {section === 'flags' && <FlagsEditor draft={draft} update={update} />}
        {section === 'settings' && <SettingsEditor draft={draft} update={update} />}
        {section === 'media' && <Placeholder title="Media Library" icon={FileImage} text="Media storage is ready for the IEEE Portal asset API." />}
        {section === 'users' && <UsersEditor user={user} />}
        {section === 'activity' && <ActivityLog />}
      </div>
      {isDirty && <div className="admin-savebar"><span>Changes are saved as a private draft until published.</span><div><button className="admin-secondary-button" onClick={resetDraft}>Discard</button><button className="admin-secondary-button" onClick={saveDraft}><Save size={15} /> Save Draft</button><button className="admin-primary-button" disabled={!canWrite} onClick={publishChanges}><Check size={15} /> Publish</button></div></div>}
      {toast && <div className="admin-toast"><Check size={15} />{toast}</div>}
    </main>
  </div>;
}

function Overview({ draft, templateCount }) { return <div className="admin-stack"><div className="admin-page-intro"><span className="admin-kicker">Control plane</span><h2>Keep the product coherent.</h2><p>Manage product content, presentation systems, and feature behavior without touching implementation code.</p></div><div className="admin-stat-grid">{[['Presentations', '—', 'Connect analytics adapter'], ['Templates', templateCount, 'Active in workspace'], ['Themes', draft.themes.filter((item) => item.active).length, 'Available systems'], ['AI generations', '—', 'Connect generation metrics']].map(([label, value, hint]) => <div className="admin-stat" key={label}><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>)}</div><div className="admin-panel"><div className="admin-panel-heading"><div><span className="admin-kicker">Integration status</span><h3>Ready for portal APIs</h3></div><span className="admin-status-dot">Local adapter active</span></div><p className="admin-muted">Drafts and published configuration currently persist in this browser. Replace the config adapter with the IEEE Portal API for shared production state, audit persistence, media storage, and server-enforced permissions.</p></div></div>; }

function LandingEditor({ draft, update }) { const moveStep = (index, direction) => { const steps = [...draft.landing.steps]; const target = index + direction; if (target < 0 || target >= steps.length) return; [steps[index], steps[target]] = [steps[target], steps[index]]; update('landing.steps', steps); }; return <div className="admin-two-column"><div className="admin-stack"><EditorSection title="Hero content" description="The landing page consumes these published values."><Field label="Eyebrow" value={draft.landing.eyebrow} onChange={(value) => update('landing.eyebrow', value)} /><Field label="Title" value={draft.landing.title} onChange={(value) => update('landing.title', value)} /><Field label="Tagline" value={draft.landing.tagline} onChange={(value) => update('landing.tagline', value)} /><TextArea label="Description" value={draft.landing.description} onChange={(value) => update('landing.description', value)} /><Field label="CTA label" value={draft.landing.ctaLabel} onChange={(value) => update('landing.ctaLabel', value)} /></EditorSection><EditorSection title="Workflow steps" description="Reorder the live landing journey without changing code.">{draft.landing.steps.map((step, index) => <div className="admin-list-row" key={`${step.title}-${index}`}><div><strong>{step.title}</strong><small>{step.description}</small></div><div className="admin-row-actions"><button className="admin-icon-button" disabled={index === 0} onClick={() => moveStep(index, -1)} aria-label={`Move ${step.title} up`}>↑</button><button className="admin-icon-button" disabled={index === draft.landing.steps.length - 1} onClick={() => moveStep(index, 1)} aria-label={`Move ${step.title} down`}>↓</button></div></div>)}</EditorSection><EditorSection title="Sections" description="Disable sections without deleting their content."><Toggle label="Feature tour" value={draft.landing.featureTourVisible} onChange={(value) => update('landing.featureTourVisible', value)} /><Toggle label="Create with AI" value={draft.landing.aiSectionVisible} onChange={(value) => update('landing.aiSectionVisible', value)} /><Toggle label="Footer" value={draft.landing.footerVisible} onChange={(value) => update('landing.footerVisible', value)} /></EditorSection></div><div className="admin-preview-pane"><span className="admin-kicker">Preview</span><div className="admin-mini-landing"><span>{draft.landing.eyebrow}</span><h2>{draft.landing.title}</h2><h3>{draft.landing.tagline}</h3><p>{draft.landing.description}</p><button>{draft.landing.ctaLabel}</button></div></div></div>; }

function DashboardEditor({ draft, update }) { const moveSection = (index, direction) => { const order = [...draft.dashboard.sectionOrder]; const target = index + direction; if (target < 0 || target >= order.length) return; [order[index], order[target]] = [order[target], order[index]]; update('dashboard.sectionOrder', order); }; return <div className="admin-stack"><EditorSection title="Workspace navigation" description="Published labels are used by the Dashboard sidebar.">{draft.dashboard.sectionOrder.map((id, index) => <div className="admin-list-row" key={id}><div><strong>{draft.dashboard.labels[id]}</strong><small>{draft.dashboard.descriptions[id]}</small></div><div className="admin-row-actions"><button className="admin-icon-button" disabled={index === 0} onClick={() => moveSection(index, -1)} aria-label={`Move ${draft.dashboard.labels[id]} up`}>↑</button><button className="admin-icon-button" disabled={index === draft.dashboard.sectionOrder.length - 1} onClick={() => moveSection(index, 1)} aria-label={`Move ${draft.dashboard.labels[id]} down`}>↓</button></div></div>)}{Object.entries(draft.dashboard.labels).map(([id, value]) => <Field key={`label-${id}`} label={`${id} label`} value={value} onChange={(next) => update(`dashboard.labels.${id}`, next)} />)}</EditorSection><EditorSection title="Feature visibility" description="Hide a workflow while keeping its data intact.">{Object.entries(draft.dashboard.visibleSections).map(([id, value]) => <Toggle key={id} label={draft.dashboard.labels[id]} value={value} onChange={(next) => update(`dashboard.visibleSections.${id}`, next)} />)}</EditorSection></div>; }

function TemplatesEditor({ draft, update }) { const [name, setName] = useState(''); const add = () => { if (!name.trim()) return; updateDraftTemplates(update, draft, { id: `custom-${Date.now()}`, name, description: 'New admin-managed template', category: 'Custom', theme: 'default', markdown: '---\nmarp: true\ntheme: default\n---\n\n# New template', active: true, featured: false, order: draft.templates.length }); setName(''); }; const duplicate = (template) => updateDraftTemplates(update, draft, { ...template, id: `${template.id}-copy-${Date.now()}`, name: `${template.name} Copy`, order: draft.templates.length }); return <div className="admin-stack"><EditorSection title="Template manager" description="Starter templates are published through the same catalog consumed by Explore Templates."><div className="admin-inline-form"><Field label="Template name" value={name} onChange={setName} /><button className="admin-primary-button" onClick={add}><Upload size={15} /> Add template</button></div>{[...draft.templates].sort((a, b) => a.order - b.order).map((template, index) => <div className="admin-list-row" key={template.id}><div><strong>{template.name}</strong><small>{template.category} · {template.theme} · {template.featured ? 'Featured' : 'Standard'}</small></div><div className="admin-row-actions"><Toggle label="" value={template.active} onChange={(value) => update(`templates.${index}.active`, value)} /><button className="admin-icon-button" aria-label={`Duplicate ${template.name}`} onClick={() => duplicate(template)}>＋</button><button className="admin-icon-button" aria-label={`Delete ${template.name}`} onClick={() => updateDraftTemplates(update, draft, null, index)}><X size={15} /></button></div></div>)}</EditorSection></div>; }
function updateDraftTemplates(update, draft, item, removeIndex = null) { const next = draft.templates.filter((_, index) => index !== removeIndex); if (item) next.push(item); update(() => ({ ...draft, templates: next })); }

function ThemesEditor({ draft, update, activeTheme, selectedTheme, setSelectedTheme }) { const setDefault = () => update(() => ({ ...draft, themes: draft.themes.map((theme) => ({ ...theme, isDefault: theme.id === activeTheme.id })) })); return <div className="admin-two-column"><div className="admin-stack"><EditorSection title="Presentation themes" description="Edit the same theme tokens used by SlideView and thumbnails."><div className="admin-theme-list">{[...draft.themes].sort((a, b) => a.order - b.order).map((theme) => <button className={selectedTheme === theme.id ? 'admin-theme-row is-active' : 'admin-theme-row'} key={theme.id} onClick={() => setSelectedTheme(theme.id)}><span style={{ background: theme.colors.primary }} /><div><strong>{theme.name}</strong><small>{theme.category}</small></div><em>{theme.isDefault ? 'Default' : ''}</em></button>)}</div></EditorSection><EditorSection title="Theme tokens"><Field label="Name" value={activeTheme?.name || ''} onChange={(value) => update(`themes.${draft.themes.findIndex((item) => item.id === activeTheme.id)}.name`, value)} /><TextArea label="Description" value={activeTheme?.description || ''} onChange={(value) => update(`themes.${draft.themes.findIndex((item) => item.id === activeTheme.id)}.description`, value)} /><div className="admin-color-grid">{['background', 'surface', 'primary', 'secondary', 'accent', 'text'].map((key) => <label key={key}><span>{key}</span><input type="color" value={activeTheme?.colors?.[key]?.slice(0, 7) || '#ffffff'} onChange={(event) => update(`themes.${draft.themes.findIndex((item) => item.id === activeTheme.id)}.colors.${key}`, event.target.value)} /></label>)}</div><Toggle label="Active theme" value={activeTheme?.active} onChange={(value) => update(`themes.${draft.themes.findIndex((item) => item.id === activeTheme.id)}.active`, value)} /><button className="admin-secondary-button" onClick={setDefault}>Set as default theme</button></EditorSection></div><div className="admin-preview-pane"><span className="admin-kicker">Live slide preview</span><div className="admin-slide-preview"><SlideView slide={parseMarpPresentation(sampleMarkdown).slides[0]} theme={activeTheme?.id || 'default'} /></div></div></div>; }

function AIEditor({ draft, update }) { return <div className="admin-stack"><EditorSection title="Product AI settings" description="No credentials or model secrets are stored in frontend configuration."><TextArea label="Default generation instructions" value={draft.ai.defaultInstructions} onChange={(value) => update('ai.defaultInstructions', value)} /><Field label="Default theme" value={draft.ai.defaultTheme} onChange={(value) => update('ai.defaultTheme', value)} /><p className="admin-callout"><Shield size={15} />API keys, model credentials, and provider secrets must remain backend-only.</p></EditorSection></div>; }
function VisualsEditor({ draft, update }) { return <div className="admin-stack"><EditorSection title="Animation & visual policy" description="Use presets instead of arbitrary JavaScript behavior."><Select label="Preset" value={draft.animation.preset} options={['Minimal', 'Balanced', 'Dynamic']} onChange={(value) => update('animation.preset', value)} /><Toggle label="Animations enabled" value={draft.animation.enabled} onChange={(value) => update('animation.enabled', value)} /><Toggle label="Reduced motion default" value={draft.animation.reducedMotionDefault} onChange={(value) => update('animation.reducedMotionDefault', value)} /><Select label="Ambient intensity" value={draft.animation.ambientIntensity} options={['minimal', 'balanced', 'dynamic']} onChange={(value) => update('animation.ambientIntensity', value)} /></EditorSection></div>; }
function FlagsEditor({ draft, update }) { return <div className="admin-stack"><EditorSection title="Feature flags" description="Flags are product controls, not security boundaries.">{Object.entries(draft.featureFlags).map(([key, value]) => <Toggle key={key} label={key} value={value} onChange={(next) => update(`featureFlags.${key}`, next)} />)}</EditorSection></div>; }
function SettingsEditor({ draft, update }) { return <div className="admin-stack"><EditorSection title="General settings"><Field label="Product name" value={draft.site.productName} onChange={(value) => update('site.productName', value)} /><Field label="Support URL" value={draft.site.supportUrl} onChange={(value) => update('site.supportUrl', value)} /><Field label="Footer" value={draft.site.footer} onChange={(value) => update('site.footer', value)} /></EditorSection></div>; }
function UsersEditor({ user }) { return <div className="admin-stack"><EditorSection title="Users & permissions" description="The portal adapter supplies identity; production authorization must be enforced by backend APIs."><div className="admin-list-row"><div><strong>{user.name}</strong><small>{user.role} · {user.source}</small></div><span className="admin-status-dot">Adapter identity</span></div>{Object.entries(getAdminRolePermissions()).map(([role, permissions]) => <div className="admin-list-row" key={role}><div><strong>{role}</strong><small>{permissions.join(', ')}</small></div></div>)}</EditorSection></div>; }
function ActivityLog() { return <div className="admin-stack"><EditorSection title="Activity log" description="Audit events will be supplied by the portal API in production."><div className="admin-empty"><Activity size={24} /><p>No persisted audit events are available in the local adapter.</p></div></EditorSection></div>; }
function Placeholder({ title, icon: Icon, text }) { return <div className="admin-stack"><EditorSection title={title}><div className="admin-empty"><Icon size={28} /><p>{text}</p></div></EditorSection></div>; }
function EditorSection({ title, description, children }) { return <section className="admin-panel"><div className="admin-panel-heading"><div><h3>{title}</h3>{description && <p>{description}</p>}</div></div>{children}</section>; }
function Field({ label, value, onChange }) { return <label className="admin-field"><span>{label}</span><input value={value || ''} onChange={(event) => onChange(event.target.value)} /></label>; }
function TextArea({ label, value, onChange }) { return <label className="admin-field"><span>{label}</span><textarea rows={4} value={value || ''} onChange={(event) => onChange(event.target.value)} /></label>; }
function Select({ label, value, options, onChange }) { return <label className="admin-field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function Toggle({ label, value, onChange }) { return <label className="admin-toggle"><span>{label}</span><input type="checkbox" checked={Boolean(value)} onChange={(event) => onChange(event.target.checked)} /><i /></label>; }
